---
reddit_client:
  target-subreddit: "leagueoflegends"
  submission-limit: 4000
  user-agent: "replays-lol-reddit-client"
function:
  scan-interval: 60
  patterns:
  - "https?://(?:euw|na|oce|eune|br|jp|ru|tr){1}.op.gg/summoners?/(euw|na|oce|eune|br|jp|ru|tr)?/(.{3,16})"
  - "https?://u.gg/lol/profile/(euw1|eune1|na1|tr1|br1|kr1|jp1|oce1|ru1)/(.{3,16})/(?:overview)?"
  - "https?://blitz.gg/lol/profile/(euw1|eune1|na1|tr1|br1|kr1|jp1|oce1|ru1)/(.{3,16})/?"
queue:
  name: "replays-lol-reddit-bot"
  host: "localhost"
